# Generated by Django 6.0 on 2026-01-01 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_vendorprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorprofile',
            options={'ordering': ['-created_at'], 'verbose_name': '1. Vendor Profile', 'verbose_name_plural': 'Vendor Profiles'},
        ),
    ]
